### ISSUE TITLE
add sync funtionality

### ISSUE THREAD

**Issue by xaoo** [Drewsif/PiShrink#57]
If I have a 128G sd, and dd it every time I want a new backup, this will imply:

- take new dd, for 128gb it will take a long time
- use this tool to shrink it
- is copy function is used, it will take even logger time

If, sync can be implemented, it would only check changed data from a synced dd .img to the already existing shrink .img.

**Comment by Drewsif** [comment]
I've definitively thought about being able to make an image directly from the sd card so you wouldn't need to take an image. Using sync the way you described would be hard since you would need to have the images be around the same size and adding or remove a lot of data would have little to no effect on the image. I've thought about using it before I just haunt figured out the best way to get it implemented
