### ISSUE TITLE
Error: rootfs: Inodes that were part of a corrupted orphan linked list found.  

### ISSUE THREAD

**Issue by JustMeErazem** [Drewsif/PiShrink#65]
Skipping autoexpanding process...
rootfs: recovering journal
rootfs: Inodes that were part of a corrupted orphan linked list found.  

rootfs: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
        (i.e., without -a or -p options)
resize2fs 1.43.8 (1-Jan-2018)
resize2fs: Invalid argument while trying to open /dev/loop0
/usr/local/bin/pishrink.sh: line 151: [[: Couldn'tfindvalidfilesystemsuperblock.: syntax error: invalid arithmetic operator (error token is "'tfindvalidfilesystemsuperblock.")
/usr/local/bin/pishrink.sh: line 157: 3877248 - Couldn'tfindvalidfilesystemsuperblock.: syntax error: invalid arithmetic operator (error token is "'tfindvalidfilesystemsuperblock.")
resize2fs 1.43.8 (1-Jan-2018)
resize2fs: Invalid argument while trying to open /dev/loop0
Couldn't find valid filesystem superblock.
ERROR: resize2fs failed...
mount: : mount point does not exist.
mv: cannot stat '/etc/rc.local.bak': No such file or directory
umount: : no mount point specified.
losetup: /dev/loop0: detach failed: No such device or address

**Comment by techdesign** [comment]
I ran in to this error as well. You can get around this by changing to script to run e2fsck with the -y switch instead of -p, but I would prefer some sort of errorlevel checking and warning first. The man pages state that a value of 4 logically or'ed into the exit code is what this error means. If someone could modify the script to capture that exit code and kill the script with descriptive text, it would allow us to run e2fsck manually as desired....

I might attempt this later.

**Comment by Drewsif** [comment]
The image you took was corrupted. Either take the above suggestion or run `e2fsck` on your pi and take a new image.
